/* Automatically generated by tree-sitter v0.25.2 (6e0618704ad758ba2ea5822faa80bcd36fbeba3d) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 101
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_empty_statement = 1,
  anon_sym_DOLLAR = 2,
  anon_sym_EQ = 3,
  sym_identifier = 4,
  anon_sym_by = 5,
  anon_sym_COLON = 6,
  anon_sym_if = 7,
  anon_sym_in = 8,
  anon_sym_weight = 9,
  anon_sym_COMMA = 10,
  sym_comment = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_else = 14,
  anon_sym_forvalues = 15,
  anon_sym_GT = 16,
  anon_sym_LT = 17,
  anon_sym_GT_EQ = 18,
  anon_sym_LT_EQ = 19,
  anon_sym_EQ_EQ = 20,
  anon_sym_BANG_EQ = 21,
  anon_sym_PLUS = 22,
  anon_sym_DASH = 23,
  anon_sym_STAR = 24,
  anon_sym_SLASH = 25,
  sym_number = 26,
  anon_sym_DQUOTE = 27,
  aux_sym_string_token1 = 28,
  anon_sym_SQUOTE = 29,
  aux_sym_string_token2 = 30,
  sym_range = 31,
  anon_sym_LPAREN = 32,
  anon_sym_RPAREN = 33,
  sym_source_file = 34,
  sym__statement = 35,
  sym_macro_definition = 36,
  sym_macro_reference = 37,
  sym_command = 38,
  sym__command_with_args = 39,
  sym_if_qualifier = 40,
  sym_in_qualifier = 41,
  sym_weight_qualifier = 42,
  sym_options_qualifier = 43,
  sym_stata_command = 44,
  sym_varlist = 45,
  sym_control_flow_structure = 46,
  sym_if_structure = 47,
  sym_for_structure = 48,
  sym_expression = 49,
  sym_binary_expression = 50,
  sym_string = 51,
  sym_options = 52,
  sym_option = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym__command_with_args_repeat1 = 55,
  aux_sym_varlist_repeat1 = 56,
  aux_sym_options_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_empty_statement] = "empty_statement",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [anon_sym_by] = "by",
  [anon_sym_COLON] = ":",
  [anon_sym_if] = "if",
  [anon_sym_in] = "in",
  [anon_sym_weight] = "weight",
  [anon_sym_COMMA] = ",",
  [sym_comment] = "comment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_else] = "else",
  [anon_sym_forvalues] = "forvalues",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_range] = "range",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_macro_definition] = "macro_definition",
  [sym_macro_reference] = "macro_reference",
  [sym_command] = "command",
  [sym__command_with_args] = "_command_with_args",
  [sym_if_qualifier] = "if_qualifier",
  [sym_in_qualifier] = "in_qualifier",
  [sym_weight_qualifier] = "weight_qualifier",
  [sym_options_qualifier] = "options_qualifier",
  [sym_stata_command] = "stata_command",
  [sym_varlist] = "varlist",
  [sym_control_flow_structure] = "control_flow_structure",
  [sym_if_structure] = "if_structure",
  [sym_for_structure] = "for_structure",
  [sym_expression] = "expression",
  [sym_binary_expression] = "binary_expression",
  [sym_string] = "string",
  [sym_options] = "options",
  [sym_option] = "option",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__command_with_args_repeat1] = "_command_with_args_repeat1",
  [aux_sym_varlist_repeat1] = "varlist_repeat1",
  [aux_sym_options_repeat1] = "options_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_empty_statement] = sym_empty_statement,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [anon_sym_by] = anon_sym_by,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_weight] = anon_sym_weight,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_forvalues] = anon_sym_forvalues,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_range] = sym_range,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_macro_definition] = sym_macro_definition,
  [sym_macro_reference] = sym_macro_reference,
  [sym_command] = sym_command,
  [sym__command_with_args] = sym__command_with_args,
  [sym_if_qualifier] = sym_if_qualifier,
  [sym_in_qualifier] = sym_in_qualifier,
  [sym_weight_qualifier] = sym_weight_qualifier,
  [sym_options_qualifier] = sym_options_qualifier,
  [sym_stata_command] = sym_stata_command,
  [sym_varlist] = sym_varlist,
  [sym_control_flow_structure] = sym_control_flow_structure,
  [sym_if_structure] = sym_if_structure,
  [sym_for_structure] = sym_for_structure,
  [sym_expression] = sym_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_string] = sym_string,
  [sym_options] = sym_options,
  [sym_option] = sym_option,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__command_with_args_repeat1] = aux_sym__command_with_args_repeat1,
  [aux_sym_varlist_repeat1] = aux_sym_varlist_repeat1,
  [aux_sym_options_repeat1] = aux_sym_options_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_empty_statement] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_by] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_weight] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_forvalues] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_macro_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym__command_with_args] = {
    .visible = false,
    .named = true,
  },
  [sym_if_qualifier] = {
    .visible = true,
    .named = true,
  },
  [sym_in_qualifier] = {
    .visible = true,
    .named = true,
  },
  [sym_weight_qualifier] = {
    .visible = true,
    .named = true,
  },
  [sym_options_qualifier] = {
    .visible = true,
    .named = true,
  },
  [sym_stata_command] = {
    .visible = true,
    .named = true,
  },
  [sym_varlist] = {
    .visible = true,
    .named = true,
  },
  [sym_control_flow_structure] = {
    .visible = true,
    .named = true,
  },
  [sym_if_structure] = {
    .visible = true,
    .named = true,
  },
  [sym_for_structure] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_options] = {
    .visible = true,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__command_with_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_varlist_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_options_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_left = 1,
  field_operator = 2,
  field_right = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 5,
  [13] = 9,
  [14] = 4,
  [15] = 8,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 4,
  [33] = 33,
  [34] = 34,
  [35] = 9,
  [36] = 36,
  [37] = 37,
  [38] = 5,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 8,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 49,
  [58] = 58,
  [59] = 49,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 33,
  [70] = 34,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 75,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 79,
  [92] = 92,
  [93] = 82,
  [94] = 79,
  [95] = 75,
  [96] = 82,
  [97] = 84,
  [98] = 85,
  [99] = 84,
  [100] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '!', 5,
        '"', 69,
        '$', 18,
        '\'', 75,
        '(', 82,
        ')', 83,
        '*', 65,
        '+', 63,
        ',', 46,
        '-', 64,
        '/', 66,
        ':', 42,
        ';', 17,
        '<', 58,
        '=', 20,
        '>', 57,
        'b', 39,
        'e', 30,
        'f', 32,
        'i', 25,
        'w', 22,
        '{', 53,
        '}', 54,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 5,
        '"', 69,
        '$', 18,
        '\'', 75,
        ')', 83,
        '*', 65,
        '+', 63,
        '-', 64,
        '/', 66,
        ':', 42,
        '<', 58,
        '=', 6,
        '>', 57,
        '{', 53,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(50);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(62);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(61);
      END_STATE();
    case 7:
      if (lookahead == '-' ||
          lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '-' ||
          lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 11:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '!', 5,
        '$', 18,
        '(', 82,
        '*', 65,
        '+', 63,
        ',', 46,
        '-', 64,
        '/', 66,
        ';', 17,
        '<', 58,
        '=', 6,
        '>', 57,
        'b', 39,
        'f', 32,
        'i', 25,
        'w', 22,
        '}', 54,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 12:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '!', 5,
        '$', 18,
        ')', 83,
        '*', 65,
        '+', 63,
        '-', 64,
        '/', 66,
        ';', 17,
        '<', 58,
        '=', 6,
        '>', 57,
        'b', 39,
        'f', 32,
        'i', 26,
        '{', 53,
        '}', 54,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 13:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '!', 5,
        '$', 18,
        '*', 65,
        '+', 63,
        ',', 46,
        '-', 64,
        '/', 66,
        ';', 17,
        '<', 58,
        '=', 20,
        '>', 57,
        'b', 39,
        'f', 32,
        'i', 25,
        'w', 22,
        '}', 54,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 14:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '$', 18,
        ',', 46,
        '/', 2,
        ';', 17,
        '=', 19,
        'b', 39,
        'f', 32,
        'i', 25,
        'w', 22,
        '}', 54,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '$', 18,
        '/', 2,
        ';', 17,
        'b', 39,
        'e', 30,
        'f', 32,
        'i', 26,
        '}', 54,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_empty_statement);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(61);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(43);
      if (lookahead == 'n') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_by);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_in);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_weight);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(74);
      if (lookahead == '"') ADVANCE(50);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(50);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(74);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(80);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_forvalues);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(50);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '*') ADVANCE(70);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead != 0) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '*') ADVANCE(70);
      if (lookahead != 0) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(71);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == '*') ADVANCE(76);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead != 0) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == '*') ADVANCE(76);
      if (lookahead != 0) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(77);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(80);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(78);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_range);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 13},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 14},
  [34] = {.lex_state = 14},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 11},
  [37] = {.lex_state = 11},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 11},
  [40] = {.lex_state = 14},
  [41] = {.lex_state = 11},
  [42] = {.lex_state = 12},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 12},
  [45] = {.lex_state = 12},
  [46] = {.lex_state = 11},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 11},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 15},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 15},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 12},
  [63] = {.lex_state = 12},
  [64] = {.lex_state = 12},
  [65] = {.lex_state = 12},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 12},
  [68] = {.lex_state = 12},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 14},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 73},
  [85] = {.lex_state = 79},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 14},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 12},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 12},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 73},
  [98] = {.lex_state = 79},
  [99] = {.lex_state = 73},
  [100] = {.lex_state = 79},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_empty_statement] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_by] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_weight] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_forvalues] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(83),
    [sym__statement] = STATE(23),
    [sym_macro_definition] = STATE(23),
    [sym_command] = STATE(23),
    [sym__command_with_args] = STATE(61),
    [sym_stata_command] = STATE(10),
    [sym_control_flow_structure] = STATE(23),
    [sym_if_structure] = STATE(62),
    [sym_for_structure] = STATE(62),
    [aux_sym_source_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_empty_statement] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_by] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [sym_comment] = ACTIONS(7),
    [anon_sym_forvalues] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(23), 1,
      anon_sym_in,
    ACTIONS(25), 1,
      anon_sym_weight,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(29), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(21), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(19), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    STATE(24), 5,
      sym_if_qualifier,
      sym_in_qualifier,
      sym_weight_qualifier,
      sym_options_qualifier,
      aux_sym__command_with_args_repeat1,
    ACTIONS(31), 7,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [44] = 8,
    ACTIONS(23), 1,
      anon_sym_in,
    ACTIONS(25), 1,
      anon_sym_weight,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(29), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(35), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(33), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    STATE(29), 5,
      sym_if_qualifier,
      sym_in_qualifier,
      sym_weight_qualifier,
      sym_options_qualifier,
      aux_sym__command_with_args_repeat1,
    ACTIONS(31), 7,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [88] = 2,
    ACTIONS(39), 10,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(37), 13,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [116] = 2,
    ACTIONS(43), 9,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(41), 13,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [143] = 4,
    ACTIONS(29), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(45), 6,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(47), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
    ACTIONS(31), 7,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [174] = 4,
    ACTIONS(29), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(49), 6,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(51), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
    ACTIONS(31), 7,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [205] = 2,
    ACTIONS(55), 9,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(53), 13,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [232] = 2,
    ACTIONS(59), 9,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(57), 13,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [259] = 9,
    ACTIONS(23), 1,
      anon_sym_in,
    ACTIONS(25), 1,
      anon_sym_weight,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(63), 1,
      anon_sym_EQ,
    STATE(17), 1,
      sym_varlist,
    STATE(34), 2,
      sym_macro_reference,
      aux_sym_varlist_repeat1,
    ACTIONS(65), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(61), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    STATE(18), 5,
      sym_if_qualifier,
      sym_in_qualifier,
      sym_weight_qualifier,
      sym_options_qualifier,
      aux_sym__command_with_args_repeat1,
  [299] = 4,
    ACTIONS(71), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(69), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(67), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(73), 7,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [327] = 2,
    ACTIONS(43), 7,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(41), 12,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [351] = 2,
    ACTIONS(59), 7,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(57), 12,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [375] = 2,
    ACTIONS(39), 7,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(37), 12,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [399] = 2,
    ACTIONS(55), 7,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(53), 12,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [423] = 11,
    ACTIONS(80), 1,
      anon_sym_DOLLAR,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(86), 1,
      anon_sym_by,
    ACTIONS(89), 1,
      anon_sym_if,
    ACTIONS(92), 1,
      anon_sym_forvalues,
    STATE(10), 1,
      sym_stata_command,
    STATE(61), 1,
      sym__command_with_args,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(77), 2,
      sym_empty_statement,
      sym_comment,
    STATE(62), 2,
      sym_if_structure,
      sym_for_structure,
    STATE(16), 5,
      sym__statement,
      sym_macro_definition,
      sym_command,
      sym_control_flow_structure,
      aux_sym_source_file_repeat1,
  [464] = 7,
    ACTIONS(23), 1,
      anon_sym_in,
    ACTIONS(25), 1,
      anon_sym_weight,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(97), 1,
      anon_sym_EQ,
    ACTIONS(99), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(95), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    STATE(20), 5,
      sym_if_qualifier,
      sym_in_qualifier,
      sym_weight_qualifier,
      sym_options_qualifier,
      aux_sym__command_with_args_repeat1,
  [497] = 6,
    ACTIONS(23), 1,
      anon_sym_in,
    ACTIONS(25), 1,
      anon_sym_weight,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(99), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(95), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    STATE(21), 5,
      sym_if_qualifier,
      sym_in_qualifier,
      sym_weight_qualifier,
      sym_options_qualifier,
      aux_sym__command_with_args_repeat1,
  [527] = 11,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_by,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_forvalues,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      sym_stata_command,
    STATE(61), 1,
      sym__command_with_args,
    ACTIONS(101), 2,
      sym_empty_statement,
      sym_comment,
    STATE(62), 2,
      sym_if_structure,
      sym_for_structure,
    STATE(22), 5,
      sym__statement,
      sym_macro_definition,
      sym_command,
      sym_control_flow_structure,
      aux_sym_source_file_repeat1,
  [567] = 6,
    ACTIONS(23), 1,
      anon_sym_in,
    ACTIONS(25), 1,
      anon_sym_weight,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(21), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(19), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    STATE(21), 5,
      sym_if_qualifier,
      sym_in_qualifier,
      sym_weight_qualifier,
      sym_options_qualifier,
      aux_sym__command_with_args_repeat1,
  [597] = 7,
    ACTIONS(109), 1,
      anon_sym_if,
    ACTIONS(112), 1,
      anon_sym_in,
    ACTIONS(115), 1,
      anon_sym_weight,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(107), 3,
      sym_identifier,
      anon_sym_by,
      anon_sym_forvalues,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    STATE(21), 5,
      sym_if_qualifier,
      sym_in_qualifier,
      sym_weight_qualifier,
      sym_options_qualifier,
      aux_sym__command_with_args_repeat1,
  [629] = 11,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_by,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_forvalues,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      sym_stata_command,
    STATE(61), 1,
      sym__command_with_args,
    ACTIONS(121), 2,
      sym_empty_statement,
      sym_comment,
    STATE(62), 2,
      sym_if_structure,
      sym_for_structure,
    STATE(16), 5,
      sym__statement,
      sym_macro_definition,
      sym_command,
      sym_control_flow_structure,
      aux_sym_source_file_repeat1,
  [669] = 11,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_by,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_forvalues,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_stata_command,
    STATE(61), 1,
      sym__command_with_args,
    ACTIONS(121), 2,
      sym_empty_statement,
      sym_comment,
    STATE(62), 2,
      sym_if_structure,
      sym_for_structure,
    STATE(16), 5,
      sym__statement,
      sym_macro_definition,
      sym_command,
      sym_control_flow_structure,
      aux_sym_source_file_repeat1,
  [709] = 6,
    ACTIONS(23), 1,
      anon_sym_in,
    ACTIONS(25), 1,
      anon_sym_weight,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(35), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(33), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    STATE(21), 5,
      sym_if_qualifier,
      sym_in_qualifier,
      sym_weight_qualifier,
      sym_options_qualifier,
      aux_sym__command_with_args_repeat1,
  [739] = 11,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_by,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_forvalues,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      sym_stata_command,
    STATE(61), 1,
      sym__command_with_args,
    ACTIONS(121), 2,
      sym_empty_statement,
      sym_comment,
    STATE(62), 2,
      sym_if_structure,
      sym_for_structure,
    STATE(16), 5,
      sym__statement,
      sym_macro_definition,
      sym_command,
      sym_control_flow_structure,
      aux_sym_source_file_repeat1,
  [779] = 11,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_by,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_forvalues,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      sym_stata_command,
    STATE(61), 1,
      sym__command_with_args,
    ACTIONS(121), 2,
      sym_empty_statement,
      sym_comment,
    STATE(62), 2,
      sym_if_structure,
      sym_for_structure,
    STATE(16), 5,
      sym__statement,
      sym_macro_definition,
      sym_command,
      sym_control_flow_structure,
      aux_sym_source_file_repeat1,
  [819] = 11,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_by,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_forvalues,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      sym_stata_command,
    STATE(61), 1,
      sym__command_with_args,
    ACTIONS(121), 2,
      sym_empty_statement,
      sym_comment,
    STATE(62), 2,
      sym_if_structure,
      sym_for_structure,
    STATE(16), 5,
      sym__statement,
      sym_macro_definition,
      sym_command,
      sym_control_flow_structure,
      aux_sym_source_file_repeat1,
  [859] = 11,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_by,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_forvalues,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      sym_stata_command,
    STATE(61), 1,
      sym__command_with_args,
    ACTIONS(133), 2,
      sym_empty_statement,
      sym_comment,
    STATE(62), 2,
      sym_if_structure,
      sym_for_structure,
    STATE(25), 5,
      sym__statement,
      sym_macro_definition,
      sym_command,
      sym_control_flow_structure,
      aux_sym_source_file_repeat1,
  [899] = 6,
    ACTIONS(23), 1,
      anon_sym_in,
    ACTIONS(25), 1,
      anon_sym_weight,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(139), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    STATE(21), 5,
      sym_if_qualifier,
      sym_in_qualifier,
      sym_weight_qualifier,
      sym_options_qualifier,
      aux_sym__command_with_args_repeat1,
  [929] = 11,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_by,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_forvalues,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      sym_stata_command,
    STATE(61), 1,
      sym__command_with_args,
    ACTIONS(141), 2,
      sym_empty_statement,
      sym_comment,
    STATE(62), 2,
      sym_if_structure,
      sym_for_structure,
    STATE(27), 5,
      sym__statement,
      sym_macro_definition,
      sym_command,
      sym_control_flow_structure,
      aux_sym_source_file_repeat1,
  [969] = 11,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_by,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_forvalues,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      sym_stata_command,
    STATE(61), 1,
      sym__command_with_args,
    ACTIONS(143), 2,
      sym_empty_statement,
      sym_comment,
    STATE(62), 2,
      sym_if_structure,
      sym_for_structure,
    STATE(26), 5,
      sym__statement,
      sym_macro_definition,
      sym_command,
      sym_control_flow_structure,
      aux_sym_source_file_repeat1,
  [1009] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(37), 12,
      anon_sym_DOLLAR,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [1032] = 5,
    ACTIONS(149), 1,
      anon_sym_DOLLAR,
    ACTIONS(152), 1,
      sym_identifier,
    STATE(33), 2,
      sym_macro_reference,
      aux_sym_varlist_repeat1,
    ACTIONS(155), 5,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
    ACTIONS(147), 6,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
  [1058] = 3,
    STATE(33), 2,
      sym_macro_reference,
      aux_sym_varlist_repeat1,
    ACTIONS(159), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
    ACTIONS(157), 7,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
  [1080] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(57), 9,
      anon_sym_LBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [1100] = 3,
    STATE(39), 1,
      aux_sym_options_repeat1,
    ACTIONS(161), 6,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(163), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
  [1120] = 3,
    ACTIONS(169), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 6,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(167), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
  [1140] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(41), 9,
      anon_sym_LBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [1160] = 4,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_options_repeat1,
    ACTIONS(171), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(173), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
  [1182] = 2,
    ACTIONS(180), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
    ACTIONS(178), 7,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
  [1200] = 3,
    STATE(36), 1,
      aux_sym_options_repeat1,
    ACTIONS(182), 6,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(184), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
  [1220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(53), 9,
      anon_sym_LBRACE,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [1240] = 2,
    ACTIONS(186), 6,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(188), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
  [1257] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_LBRACE,
    ACTIONS(192), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(194), 7,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1278] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    ACTIONS(192), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(194), 7,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1299] = 2,
    ACTIONS(171), 6,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(173), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
  [1316] = 2,
    ACTIONS(198), 6,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(200), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
  [1333] = 2,
    ACTIONS(202), 6,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      anon_sym_COMMA,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(204), 6,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_in,
      anon_sym_weight,
      anon_sym_forvalues,
  [1350] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_DOLLAR,
    ACTIONS(210), 1,
      anon_sym_DQUOTE,
    ACTIONS(212), 1,
      anon_sym_SQUOTE,
    STATE(15), 1,
      sym_expression,
    ACTIONS(208), 2,
      sym_identifier,
      sym_number,
    STATE(13), 3,
      sym_macro_reference,
      sym_binary_expression,
      sym_string,
  [1375] = 3,
    ACTIONS(218), 1,
      anon_sym_else,
    ACTIONS(216), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(214), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
  [1392] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_DOLLAR,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    ACTIONS(226), 1,
      anon_sym_SQUOTE,
    STATE(7), 1,
      sym_expression,
    ACTIONS(222), 2,
      sym_identifier,
      sym_number,
    STATE(9), 3,
      sym_macro_reference,
      sym_binary_expression,
      sym_string,
  [1417] = 3,
    ACTIONS(232), 1,
      anon_sym_else,
    ACTIONS(230), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(228), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
  [1434] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DOLLAR,
    ACTIONS(238), 1,
      anon_sym_DQUOTE,
    ACTIONS(240), 1,
      anon_sym_SQUOTE,
    STATE(45), 1,
      sym_expression,
    ACTIONS(236), 2,
      sym_identifier,
      sym_number,
    STATE(35), 3,
      sym_macro_reference,
      sym_binary_expression,
      sym_string,
  [1459] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_DOLLAR,
    ACTIONS(210), 1,
      anon_sym_DQUOTE,
    ACTIONS(212), 1,
      anon_sym_SQUOTE,
    STATE(11), 1,
      sym_expression,
    ACTIONS(208), 2,
      sym_identifier,
      sym_number,
    STATE(13), 3,
      sym_macro_reference,
      sym_binary_expression,
      sym_string,
  [1484] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_DOLLAR,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    ACTIONS(226), 1,
      anon_sym_SQUOTE,
    STATE(6), 1,
      sym_expression,
    ACTIONS(222), 2,
      sym_identifier,
      sym_number,
    STATE(9), 3,
      sym_macro_reference,
      sym_binary_expression,
      sym_string,
  [1509] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_DOLLAR,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    ACTIONS(226), 1,
      anon_sym_SQUOTE,
    STATE(2), 1,
      sym_expression,
    ACTIONS(222), 2,
      sym_identifier,
      sym_number,
    STATE(9), 3,
      sym_macro_reference,
      sym_binary_expression,
      sym_string,
  [1534] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DOLLAR,
    ACTIONS(238), 1,
      anon_sym_DQUOTE,
    ACTIONS(240), 1,
      anon_sym_SQUOTE,
    STATE(42), 1,
      sym_expression,
    ACTIONS(236), 2,
      sym_identifier,
      sym_number,
    STATE(35), 3,
      sym_macro_reference,
      sym_binary_expression,
      sym_string,
  [1559] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DOLLAR,
    ACTIONS(238), 1,
      anon_sym_DQUOTE,
    ACTIONS(240), 1,
      anon_sym_SQUOTE,
    STATE(44), 1,
      sym_expression,
    ACTIONS(236), 2,
      sym_identifier,
      sym_number,
    STATE(35), 3,
      sym_macro_reference,
      sym_binary_expression,
      sym_string,
  [1584] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_DOLLAR,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    ACTIONS(226), 1,
      anon_sym_SQUOTE,
    STATE(8), 1,
      sym_expression,
    ACTIONS(222), 2,
      sym_identifier,
      sym_number,
    STATE(9), 3,
      sym_macro_reference,
      sym_binary_expression,
      sym_string,
  [1609] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_DOLLAR,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    ACTIONS(226), 1,
      anon_sym_SQUOTE,
    STATE(3), 1,
      sym_expression,
    ACTIONS(222), 2,
      sym_identifier,
      sym_number,
    STATE(9), 3,
      sym_macro_reference,
      sym_binary_expression,
      sym_string,
  [1634] = 2,
    ACTIONS(244), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(242), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
  [1648] = 2,
    ACTIONS(248), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(246), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
  [1662] = 2,
    ACTIONS(252), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(250), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
  [1676] = 2,
    ACTIONS(256), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(254), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
  [1690] = 2,
    ACTIONS(260), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(258), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
  [1704] = 2,
    ACTIONS(264), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(262), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
  [1718] = 2,
    ACTIONS(268), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(266), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
  [1732] = 2,
    ACTIONS(272), 4,
      sym_identifier,
      anon_sym_by,
      anon_sym_if,
      anon_sym_forvalues,
    ACTIONS(270), 5,
      ts_builtin_sym_end,
      sym_empty_statement,
      anon_sym_DOLLAR,
      sym_comment,
      anon_sym_RBRACE,
  [1746] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_COLON,
    ACTIONS(274), 1,
      anon_sym_DOLLAR,
    ACTIONS(277), 1,
      sym_identifier,
    STATE(69), 2,
      sym_macro_reference,
      aux_sym_varlist_repeat1,
  [1763] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_COLON,
    ACTIONS(234), 1,
      anon_sym_DOLLAR,
    ACTIONS(280), 1,
      sym_identifier,
    STATE(69), 2,
      sym_macro_reference,
      aux_sym_varlist_repeat1,
  [1780] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DOLLAR,
    ACTIONS(282), 1,
      sym_identifier,
    STATE(80), 1,
      sym_varlist,
    STATE(70), 2,
      sym_macro_reference,
      aux_sym_varlist_repeat1,
  [1797] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym_identifier,
    STATE(41), 1,
      sym_option,
    STATE(47), 1,
      sym_options,
  [1810] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_identifier,
    STATE(10), 1,
      sym_stata_command,
    STATE(68), 1,
      sym__command_with_args,
  [1823] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym_identifier,
    STATE(46), 1,
      sym_option,
  [1833] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_DQUOTE,
  [1840] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_DQUOTE,
  [1847] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_EQ,
  [1854] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_LBRACE,
  [1861] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      sym_identifier,
  [1868] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_COLON,
  [1875] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      sym_identifier,
  [1882] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_SQUOTE,
  [1889] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      ts_builtin_sym_end,
  [1896] = 2,
    ACTIONS(304), 1,
      sym_comment,
    ACTIONS(306), 1,
      aux_sym_string_token1,
  [1903] = 2,
    ACTIONS(304), 1,
      sym_comment,
    ACTIONS(308), 1,
      aux_sym_string_token2,
  [1910] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_LBRACE,
  [1917] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      sym_identifier,
  [1924] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_EQ,
  [1931] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      anon_sym_LBRACE,
  [1938] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      sym_range,
  [1945] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      sym_identifier,
  [1952] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      sym_range,
  [1959] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_SQUOTE,
  [1966] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      sym_identifier,
  [1973] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_DQUOTE,
  [1980] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_SQUOTE,
  [1987] = 2,
    ACTIONS(304), 1,
      sym_comment,
    ACTIONS(328), 1,
      aux_sym_string_token1,
  [1994] = 2,
    ACTIONS(304), 1,
      sym_comment,
    ACTIONS(330), 1,
      aux_sym_string_token2,
  [2001] = 2,
    ACTIONS(304), 1,
      sym_comment,
    ACTIONS(332), 1,
      aux_sym_string_token1,
  [2008] = 2,
    ACTIONS(304), 1,
      sym_comment,
    ACTIONS(334), 1,
      aux_sym_string_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 116,
  [SMALL_STATE(6)] = 143,
  [SMALL_STATE(7)] = 174,
  [SMALL_STATE(8)] = 205,
  [SMALL_STATE(9)] = 232,
  [SMALL_STATE(10)] = 259,
  [SMALL_STATE(11)] = 299,
  [SMALL_STATE(12)] = 327,
  [SMALL_STATE(13)] = 351,
  [SMALL_STATE(14)] = 375,
  [SMALL_STATE(15)] = 399,
  [SMALL_STATE(16)] = 423,
  [SMALL_STATE(17)] = 464,
  [SMALL_STATE(18)] = 497,
  [SMALL_STATE(19)] = 527,
  [SMALL_STATE(20)] = 567,
  [SMALL_STATE(21)] = 597,
  [SMALL_STATE(22)] = 629,
  [SMALL_STATE(23)] = 669,
  [SMALL_STATE(24)] = 709,
  [SMALL_STATE(25)] = 739,
  [SMALL_STATE(26)] = 779,
  [SMALL_STATE(27)] = 819,
  [SMALL_STATE(28)] = 859,
  [SMALL_STATE(29)] = 899,
  [SMALL_STATE(30)] = 929,
  [SMALL_STATE(31)] = 969,
  [SMALL_STATE(32)] = 1009,
  [SMALL_STATE(33)] = 1032,
  [SMALL_STATE(34)] = 1058,
  [SMALL_STATE(35)] = 1080,
  [SMALL_STATE(36)] = 1100,
  [SMALL_STATE(37)] = 1120,
  [SMALL_STATE(38)] = 1140,
  [SMALL_STATE(39)] = 1160,
  [SMALL_STATE(40)] = 1182,
  [SMALL_STATE(41)] = 1200,
  [SMALL_STATE(42)] = 1220,
  [SMALL_STATE(43)] = 1240,
  [SMALL_STATE(44)] = 1257,
  [SMALL_STATE(45)] = 1278,
  [SMALL_STATE(46)] = 1299,
  [SMALL_STATE(47)] = 1316,
  [SMALL_STATE(48)] = 1333,
  [SMALL_STATE(49)] = 1350,
  [SMALL_STATE(50)] = 1375,
  [SMALL_STATE(51)] = 1392,
  [SMALL_STATE(52)] = 1417,
  [SMALL_STATE(53)] = 1434,
  [SMALL_STATE(54)] = 1459,
  [SMALL_STATE(55)] = 1484,
  [SMALL_STATE(56)] = 1509,
  [SMALL_STATE(57)] = 1534,
  [SMALL_STATE(58)] = 1559,
  [SMALL_STATE(59)] = 1584,
  [SMALL_STATE(60)] = 1609,
  [SMALL_STATE(61)] = 1634,
  [SMALL_STATE(62)] = 1648,
  [SMALL_STATE(63)] = 1662,
  [SMALL_STATE(64)] = 1676,
  [SMALL_STATE(65)] = 1690,
  [SMALL_STATE(66)] = 1704,
  [SMALL_STATE(67)] = 1718,
  [SMALL_STATE(68)] = 1732,
  [SMALL_STATE(69)] = 1746,
  [SMALL_STATE(70)] = 1763,
  [SMALL_STATE(71)] = 1780,
  [SMALL_STATE(72)] = 1797,
  [SMALL_STATE(73)] = 1810,
  [SMALL_STATE(74)] = 1823,
  [SMALL_STATE(75)] = 1833,
  [SMALL_STATE(76)] = 1840,
  [SMALL_STATE(77)] = 1847,
  [SMALL_STATE(78)] = 1854,
  [SMALL_STATE(79)] = 1861,
  [SMALL_STATE(80)] = 1868,
  [SMALL_STATE(81)] = 1875,
  [SMALL_STATE(82)] = 1882,
  [SMALL_STATE(83)] = 1889,
  [SMALL_STATE(84)] = 1896,
  [SMALL_STATE(85)] = 1903,
  [SMALL_STATE(86)] = 1910,
  [SMALL_STATE(87)] = 1917,
  [SMALL_STATE(88)] = 1924,
  [SMALL_STATE(89)] = 1931,
  [SMALL_STATE(90)] = 1938,
  [SMALL_STATE(91)] = 1945,
  [SMALL_STATE(92)] = 1952,
  [SMALL_STATE(93)] = 1959,
  [SMALL_STATE(94)] = 1966,
  [SMALL_STATE(95)] = 1973,
  [SMALL_STATE(96)] = 1980,
  [SMALL_STATE(97)] = 1987,
  [SMALL_STATE(98)] = 1994,
  [SMALL_STATE(99)] = 2001,
  [SMALL_STATE(100)] = 2008,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_with_args, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_with_args, 3, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_with_args, 4, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_with_args, 4, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_reference, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_reference, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_qualifier, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_qualifier, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_weight_qualifier, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_weight_qualifier, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_with_args, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_with_args, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_definition, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_with_args, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_with_args, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__command_with_args_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__command_with_args_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__command_with_args_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__command_with_args_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__command_with_args_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__command_with_args_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_with_args, 5, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_with_args, 5, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_varlist_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_varlist_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_varlist_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_varlist_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varlist, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varlist, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_options, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_options, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_options_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_options_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_options_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stata_command, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stata_command, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_options, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_options, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_qualifier, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_in_qualifier, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_options_qualifier, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_options_qualifier, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 4, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 4, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_structure, 4, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_structure, 4, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_structure, 5, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_structure, 5, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_flow_structure, 1, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_control_flow_structure, 1, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_structure, 6, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_structure, 6, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_structure, 8, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_structure, 8, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_structure, 9, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_structure, 9, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_structure, 7, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_structure, 7, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_structure, 7, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_structure, 7, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 4, 0, 0),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_varlist_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_varlist_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [302] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [304] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [306] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [308] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [328] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [330] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [332] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [334] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_stata(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "stata",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
