/* Automatically generated by tree-sitter v0.25.2 (6e0618704ad758ba2ea5822faa80bcd36fbeba3d) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 88
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_regress = 2,
  anon_sym_summarize = 3,
  anon_sym_generate = 4,
  anon_sym_EQ = 5,
  anon_sym_use = 6,
  anon_sym_if = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_foreach = 10,
  anon_sym_in = 11,
  aux_sym_variable_list_token1 = 12,
  sym_variable_name = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_SLASH = 17,
  anon_sym_EQ_EQ = 18,
  anon_sym_BANG_EQ = 19,
  anon_sym_LT = 20,
  anon_sym_GT = 21,
  anon_sym_LT_EQ = 22,
  anon_sym_GT_EQ = 23,
  anon_sym_DQUOTE = 24,
  aux_sym_list_of_values_token1 = 25,
  sym_number = 26,
  aux_sym_string_token1 = 27,
  anon_sym_SQUOTE = 28,
  aux_sym_string_token2 = 29,
  anon_sym_COMMA = 30,
  anon_sym_LPAREN = 31,
  anon_sym_RPAREN = 32,
  sym_option_name = 33,
  aux_sym_comment_token1 = 34,
  anon_sym_SLASH_STAR = 35,
  aux_sym_comment_token2 = 36,
  sym_program = 37,
  sym_statement = 38,
  sym_command_statement = 39,
  sym_regress_command = 40,
  sym_summarize_command = 41,
  sym_generate_command = 42,
  sym_use_command = 43,
  sym_if_statement = 44,
  sym_foreach_loop = 45,
  sym_variable_list = 46,
  sym_expression = 47,
  sym_binary_expression = 48,
  sym_condition = 49,
  sym_list_of_values = 50,
  sym_string = 51,
  sym_options = 52,
  sym_option_value = 53,
  sym_comment = 54,
  aux_sym_program_repeat1 = 55,
  aux_sym_variable_list_repeat1 = 56,
  aux_sym_list_of_values_repeat1 = 57,
  aux_sym_list_of_values_repeat2 = 58,
  aux_sym_options_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_regress] = "regress",
  [anon_sym_summarize] = "summarize",
  [anon_sym_generate] = "generate",
  [anon_sym_EQ] = "=",
  [anon_sym_use] = "use",
  [anon_sym_if] = "if",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_foreach] = "foreach",
  [anon_sym_in] = "in",
  [aux_sym_variable_list_token1] = "variable_list_token1",
  [sym_variable_name] = "variable_name",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_list_of_values_token1] = "list_of_values_token1",
  [sym_number] = "number",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_option_name] = "option_name",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [sym_program] = "program",
  [sym_statement] = "statement",
  [sym_command_statement] = "command_statement",
  [sym_regress_command] = "regress_command",
  [sym_summarize_command] = "summarize_command",
  [sym_generate_command] = "generate_command",
  [sym_use_command] = "use_command",
  [sym_if_statement] = "if_statement",
  [sym_foreach_loop] = "foreach_loop",
  [sym_variable_list] = "variable_list",
  [sym_expression] = "expression",
  [sym_binary_expression] = "binary_expression",
  [sym_condition] = "condition",
  [sym_list_of_values] = "list_of_values",
  [sym_string] = "string",
  [sym_options] = "options",
  [sym_option_value] = "option_value",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_variable_list_repeat1] = "variable_list_repeat1",
  [aux_sym_list_of_values_repeat1] = "list_of_values_repeat1",
  [aux_sym_list_of_values_repeat2] = "list_of_values_repeat2",
  [aux_sym_options_repeat1] = "options_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_regress] = anon_sym_regress,
  [anon_sym_summarize] = anon_sym_summarize,
  [anon_sym_generate] = anon_sym_generate,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_foreach] = anon_sym_foreach,
  [anon_sym_in] = anon_sym_in,
  [aux_sym_variable_list_token1] = aux_sym_variable_list_token1,
  [sym_variable_name] = sym_variable_name,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_list_of_values_token1] = aux_sym_list_of_values_token1,
  [sym_number] = sym_number,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_option_name] = sym_option_name,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym_program] = sym_program,
  [sym_statement] = sym_statement,
  [sym_command_statement] = sym_command_statement,
  [sym_regress_command] = sym_regress_command,
  [sym_summarize_command] = sym_summarize_command,
  [sym_generate_command] = sym_generate_command,
  [sym_use_command] = sym_use_command,
  [sym_if_statement] = sym_if_statement,
  [sym_foreach_loop] = sym_foreach_loop,
  [sym_variable_list] = sym_variable_list,
  [sym_expression] = sym_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_condition] = sym_condition,
  [sym_list_of_values] = sym_list_of_values,
  [sym_string] = sym_string,
  [sym_options] = sym_options,
  [sym_option_value] = sym_option_value,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_variable_list_repeat1] = aux_sym_variable_list_repeat1,
  [aux_sym_list_of_values_repeat1] = aux_sym_list_of_values_repeat1,
  [aux_sym_list_of_values_repeat2] = aux_sym_list_of_values_repeat2,
  [aux_sym_options_repeat1] = aux_sym_options_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_regress] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_summarize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_generate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_foreach] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_variable_list_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_variable_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_list_of_values_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_option_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_command_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_regress_command] = {
    .visible = true,
    .named = true,
  },
  [sym_summarize_command] = {
    .visible = true,
    .named = true,
  },
  [sym_generate_command] = {
    .visible = true,
    .named = true,
  },
  [sym_use_command] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_foreach_loop] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_list] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_list_of_values] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_options] = {
    .visible = true,
    .named = true,
  },
  [sym_option_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_of_values_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_of_values_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_options_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 8,
  [36] = 15,
  [37] = 17,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 16,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 46,
  [51] = 48,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 78,
  [85] = 66,
  [86] = 70,
  [87] = 64,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 6,
        '"', 110,
        '\'', 116,
        '(', 120,
        ')', 121,
        '*', 101,
        '+', 99,
        ',', 119,
        '-', 100,
        '/', 103,
        ';', 43,
        '<', 106,
        '=', 54,
        '>', 107,
        'f', 27,
        'g', 12,
        'i', 20,
        'r', 13,
        's', 36,
        'u', 33,
        '{', 61,
        '}', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 6,
        '"', 110,
        '\'', 116,
        '*', 101,
        '+', 99,
        '-', 100,
        '/', 102,
        '<', 106,
        '=', 7,
        '>', 107,
        '{', 61,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(110);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(111);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(155);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(156);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(156);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(105);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(104);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(58);
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 21:
      if (lookahead == 'g') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'h') ADVANCE(63);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(10);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 37:
      if (lookahead == 'z') ADVANCE(17);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 39:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '(', 120,
        '*', 101,
        '/', 3,
        ';', 43,
        'f', 141,
        'g', 126,
        'i', 134,
        'r', 127,
        's', 150,
        'u', 147,
        '}', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 40:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '*', 101,
        ',', 119,
        '/', 3,
        ';', 43,
        '=', 53,
        'f', 87,
        'g', 72,
        'i', 80,
        'r', 73,
        's', 96,
        'u', 93,
        '}', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 41:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '*', 101,
        ',', 119,
        '/', 3,
        ';', 43,
        'f', 87,
        'g', 72,
        'i', 80,
        'r', 73,
        's', 96,
        'u', 93,
        '{', 61,
        '}', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_regress);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_regress);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_regress);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_summarize);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_summarize);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_summarize);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_generate);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_generate);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_generate);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(104);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_use);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_use);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_foreach);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_foreach);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_foreach);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_variable_list_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'a') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'a') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'a') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'c') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'e') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'e') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'e') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'e') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'e') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'e') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'e') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'f') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'g') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'h') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'i') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'm') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'm') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'n') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'o') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'r') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'r') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'r') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'r') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 's') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 's') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 's') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 't') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'u') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == 'z') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(98);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_variable_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(155);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(108);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(109);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_list_of_values_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(115);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(118);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'a') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'a') ADVANCE(149);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'a') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'c') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'e') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'e') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'e') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'e') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'e') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'e') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'e') ADVANCE(148);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'e') ADVANCE(143);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'f') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'g') ADVANCE(145);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'h') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'i') ADVANCE(151);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'm') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'm') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'n') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'o') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'r') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'r') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'r') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'r') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 's') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 's') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 's') ADVANCE(146);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 't') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'u') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == 'z') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(152);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_option_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(152);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(153);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(154);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(154);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 40},
  [10] = {.lex_state = 41},
  [11] = {.lex_state = 41},
  [12] = {.lex_state = 41},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 41},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 39},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 39},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 39},
  [24] = {.lex_state = 39},
  [25] = {.lex_state = 39},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 41},
  [60] = {.lex_state = 41},
  [61] = {.lex_state = 41},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 41},
  [64] = {.lex_state = 117},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 40},
  [70] = {.lex_state = 114},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 153},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 114},
  [87] = {.lex_state = 117},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_regress] = ACTIONS(1),
    [anon_sym_summarize] = ACTIONS(1),
    [anon_sym_generate] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_foreach] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(74),
    [sym_statement] = STATE(29),
    [sym_command_statement] = STATE(30),
    [sym_regress_command] = STATE(34),
    [sym_summarize_command] = STATE(34),
    [sym_generate_command] = STATE(34),
    [sym_use_command] = STATE(34),
    [sym_if_statement] = STATE(34),
    [sym_foreach_loop] = STATE(34),
    [sym_comment] = STATE(30),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_regress] = ACTIONS(5),
    [anon_sym_summarize] = ACTIONS(7),
    [anon_sym_generate] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_foreach] = ACTIONS(15),
    [anon_sym_STAR] = ACTIONS(17),
    [anon_sym_SLASH_STAR] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(23), 1,
      anon_sym_regress,
    ACTIONS(26), 1,
      anon_sym_summarize,
    ACTIONS(29), 1,
      anon_sym_generate,
    ACTIONS(32), 1,
      anon_sym_use,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(38), 1,
      anon_sym_foreach,
    ACTIONS(41), 1,
      anon_sym_STAR,
    ACTIONS(44), 1,
      anon_sym_SLASH_STAR,
    STATE(2), 1,
      aux_sym_program_repeat1,
    STATE(29), 1,
      sym_statement,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(30), 2,
      sym_command_statement,
      sym_comment,
    STATE(34), 6,
      sym_regress_command,
      sym_summarize_command,
      sym_generate_command,
      sym_use_command,
      sym_if_statement,
      sym_foreach_loop,
  [47] = 13,
    ACTIONS(5), 1,
      anon_sym_regress,
    ACTIONS(7), 1,
      anon_sym_summarize,
    ACTIONS(9), 1,
      anon_sym_generate,
    ACTIONS(11), 1,
      anon_sym_use,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_foreach,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_program_repeat1,
    STATE(29), 1,
      sym_statement,
    STATE(30), 2,
      sym_command_statement,
      sym_comment,
    STATE(34), 6,
      sym_regress_command,
      sym_summarize_command,
      sym_generate_command,
      sym_use_command,
      sym_if_statement,
      sym_foreach_loop,
  [93] = 13,
    ACTIONS(5), 1,
      anon_sym_regress,
    ACTIONS(7), 1,
      anon_sym_summarize,
    ACTIONS(9), 1,
      anon_sym_generate,
    ACTIONS(11), 1,
      anon_sym_use,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_foreach,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      aux_sym_program_repeat1,
    STATE(29), 1,
      sym_statement,
    STATE(30), 2,
      sym_command_statement,
      sym_comment,
    STATE(34), 6,
      sym_regress_command,
      sym_summarize_command,
      sym_generate_command,
      sym_use_command,
      sym_if_statement,
      sym_foreach_loop,
  [139] = 13,
    ACTIONS(5), 1,
      anon_sym_regress,
    ACTIONS(7), 1,
      anon_sym_summarize,
    ACTIONS(9), 1,
      anon_sym_generate,
    ACTIONS(11), 1,
      anon_sym_use,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_foreach,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_program_repeat1,
    STATE(29), 1,
      sym_statement,
    STATE(30), 2,
      sym_command_statement,
      sym_comment,
    STATE(34), 6,
      sym_regress_command,
      sym_summarize_command,
      sym_generate_command,
      sym_use_command,
      sym_if_statement,
      sym_foreach_loop,
  [185] = 13,
    ACTIONS(5), 1,
      anon_sym_regress,
    ACTIONS(7), 1,
      anon_sym_summarize,
    ACTIONS(9), 1,
      anon_sym_generate,
    ACTIONS(11), 1,
      anon_sym_use,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_foreach,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      aux_sym_program_repeat1,
    STATE(29), 1,
      sym_statement,
    STATE(30), 2,
      sym_command_statement,
      sym_comment,
    STATE(34), 6,
      sym_regress_command,
      sym_summarize_command,
      sym_generate_command,
      sym_use_command,
      sym_if_statement,
      sym_foreach_loop,
  [231] = 13,
    ACTIONS(5), 1,
      anon_sym_regress,
    ACTIONS(7), 1,
      anon_sym_summarize,
    ACTIONS(9), 1,
      anon_sym_generate,
    ACTIONS(11), 1,
      anon_sym_use,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_foreach,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_program_repeat1,
    STATE(29), 1,
      sym_statement,
    STATE(30), 2,
      sym_command_statement,
      sym_comment,
    STATE(34), 6,
      sym_regress_command,
      sym_summarize_command,
      sym_generate_command,
      sym_use_command,
      sym_if_statement,
      sym_foreach_loop,
  [277] = 2,
    ACTIONS(59), 1,
      anon_sym_SLASH,
    ACTIONS(57), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SLASH_STAR,
  [298] = 6,
    ACTIONS(65), 1,
      sym_variable_name,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      sym_variable_list,
    STATE(40), 1,
      sym_options,
    ACTIONS(61), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
    ACTIONS(63), 6,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_foreach,
  [326] = 5,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      aux_sym_variable_list_token1,
    ACTIONS(75), 1,
      sym_variable_name,
    STATE(12), 1,
      aux_sym_variable_list_repeat1,
    ACTIONS(71), 11,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_SLASH_STAR,
  [352] = 5,
    ACTIONS(73), 1,
      aux_sym_variable_list_token1,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym_variable_name,
    STATE(10), 1,
      aux_sym_variable_list_repeat1,
    ACTIONS(79), 11,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_SLASH_STAR,
  [378] = 5,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 1,
      aux_sym_variable_list_token1,
    ACTIONS(90), 1,
      sym_variable_name,
    STATE(12), 1,
      aux_sym_variable_list_repeat1,
    ACTIONS(85), 11,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_SLASH_STAR,
  [404] = 4,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(95), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(93), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_SLASH_STAR,
  [427] = 2,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      aux_sym_variable_list_token1,
    ACTIONS(85), 12,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      sym_variable_name,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_SLASH_STAR,
  [446] = 3,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(104), 1,
      anon_sym_STAR,
    ACTIONS(102), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH_STAR,
  [467] = 2,
    ACTIONS(108), 1,
      anon_sym_SLASH,
    ACTIONS(106), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [486] = 2,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(102), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [505] = 4,
    ACTIONS(116), 1,
      sym_option_name,
    STATE(23), 1,
      aux_sym_options_repeat1,
    ACTIONS(112), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 6,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_foreach,
  [527] = 3,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(28), 1,
      sym_options,
    ACTIONS(118), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [547] = 3,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      sym_options,
    ACTIONS(120), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [567] = 3,
    ACTIONS(126), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
    ACTIONS(124), 7,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_foreach,
      sym_option_name,
  [587] = 3,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(31), 1,
      sym_options,
    ACTIONS(128), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [607] = 4,
    ACTIONS(116), 1,
      sym_option_name,
    STATE(24), 1,
      aux_sym_options_repeat1,
    ACTIONS(130), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 6,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_foreach,
  [629] = 4,
    ACTIONS(138), 1,
      sym_option_name,
    STATE(24), 1,
      aux_sym_options_repeat1,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
    ACTIONS(136), 6,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_foreach,
  [651] = 2,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
    ACTIONS(143), 7,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_foreach,
      sym_option_name,
  [668] = 1,
    ACTIONS(145), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [682] = 1,
    ACTIONS(147), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [696] = 1,
    ACTIONS(149), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [710] = 2,
    ACTIONS(153), 1,
      anon_sym_SEMI,
    ACTIONS(151), 10,
      ts_builtin_sym_end,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [726] = 1,
    ACTIONS(155), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [740] = 1,
    ACTIONS(157), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [754] = 1,
    ACTIONS(159), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [768] = 1,
    ACTIONS(161), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [782] = 1,
    ACTIONS(163), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [796] = 2,
    ACTIONS(59), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 9,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [812] = 3,
    ACTIONS(110), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(165), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(102), 7,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [830] = 2,
    ACTIONS(110), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(102), 9,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [846] = 1,
    ACTIONS(167), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [860] = 1,
    ACTIONS(169), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [874] = 1,
    ACTIONS(128), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [888] = 1,
    ACTIONS(171), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [902] = 2,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 9,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [918] = 1,
    ACTIONS(173), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_regress,
      anon_sym_summarize,
      anon_sym_generate,
      anon_sym_use,
      anon_sym_if,
      anon_sym_RBRACE,
      anon_sym_foreach,
      anon_sym_STAR,
      anon_sym_SLASH_STAR,
  [932] = 4,
    ACTIONS(165), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(175), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(179), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(177), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [951] = 6,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    ACTIONS(185), 1,
      anon_sym_SQUOTE,
    STATE(44), 1,
      sym_expression,
    STATE(83), 1,
      sym_condition,
    ACTIONS(181), 2,
      sym_variable_name,
      sym_number,
    STATE(42), 2,
      sym_binary_expression,
      sym_string,
  [972] = 5,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    ACTIONS(185), 1,
      anon_sym_SQUOTE,
    STATE(36), 1,
      sym_expression,
    ACTIONS(181), 2,
      sym_variable_name,
      sym_number,
    STATE(42), 2,
      sym_binary_expression,
      sym_string,
  [990] = 5,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    ACTIONS(185), 1,
      anon_sym_SQUOTE,
    STATE(53), 1,
      sym_expression,
    ACTIONS(181), 2,
      sym_variable_name,
      sym_number,
    STATE(42), 2,
      sym_binary_expression,
      sym_string,
  [1008] = 5,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    ACTIONS(185), 1,
      anon_sym_SQUOTE,
    STATE(37), 1,
      sym_expression,
    ACTIONS(181), 2,
      sym_variable_name,
      sym_number,
    STATE(42), 2,
      sym_binary_expression,
      sym_string,
  [1026] = 5,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
    ACTIONS(191), 1,
      anon_sym_SQUOTE,
    STATE(13), 1,
      sym_expression,
    ACTIONS(187), 2,
      sym_variable_name,
      sym_number,
    STATE(16), 2,
      sym_binary_expression,
      sym_string,
  [1044] = 5,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
    ACTIONS(191), 1,
      anon_sym_SQUOTE,
    STATE(15), 1,
      sym_expression,
    ACTIONS(187), 2,
      sym_variable_name,
      sym_number,
    STATE(16), 2,
      sym_binary_expression,
      sym_string,
  [1062] = 5,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
    ACTIONS(191), 1,
      anon_sym_SQUOTE,
    STATE(17), 1,
      sym_expression,
    ACTIONS(187), 2,
      sym_variable_name,
      sym_number,
    STATE(16), 2,
      sym_binary_expression,
      sym_string,
  [1080] = 5,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
    ACTIONS(191), 1,
      anon_sym_SQUOTE,
    STATE(80), 1,
      sym_string,
    STATE(81), 1,
      sym_option_value,
    ACTIONS(193), 2,
      sym_variable_name,
      sym_number,
  [1097] = 3,
    ACTIONS(195), 1,
      anon_sym_LBRACE,
    ACTIONS(165), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(175), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1109] = 4,
    ACTIONS(197), 1,
      aux_sym_variable_list_token1,
    ACTIONS(200), 1,
      anon_sym_DQUOTE,
    ACTIONS(202), 1,
      aux_sym_list_of_values_token1,
    STATE(54), 1,
      aux_sym_list_of_values_repeat1,
  [1122] = 4,
    ACTIONS(205), 1,
      aux_sym_variable_list_token1,
    ACTIONS(207), 1,
      anon_sym_DQUOTE,
    ACTIONS(209), 1,
      aux_sym_list_of_values_token1,
    STATE(56), 1,
      aux_sym_list_of_values_repeat1,
  [1135] = 4,
    ACTIONS(211), 1,
      aux_sym_variable_list_token1,
    ACTIONS(213), 1,
      anon_sym_DQUOTE,
    ACTIONS(215), 1,
      aux_sym_list_of_values_token1,
    STATE(54), 1,
      aux_sym_list_of_values_repeat1,
  [1148] = 3,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    ACTIONS(219), 1,
      sym_number,
    STATE(79), 1,
      sym_list_of_values,
  [1158] = 3,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
    ACTIONS(191), 1,
      anon_sym_SQUOTE,
    STATE(20), 1,
      sym_string,
  [1168] = 3,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
    ACTIONS(223), 1,
      aux_sym_variable_list_token1,
    STATE(59), 1,
      aux_sym_list_of_values_repeat2,
  [1178] = 3,
    ACTIONS(226), 1,
      anon_sym_LBRACE,
    ACTIONS(228), 1,
      aux_sym_variable_list_token1,
    STATE(61), 1,
      aux_sym_list_of_values_repeat2,
  [1188] = 3,
    ACTIONS(228), 1,
      aux_sym_variable_list_token1,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      aux_sym_list_of_values_repeat2,
  [1198] = 2,
    ACTIONS(232), 1,
      sym_variable_name,
    STATE(19), 1,
      sym_variable_list,
  [1205] = 2,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
    ACTIONS(234), 1,
      aux_sym_variable_list_token1,
  [1212] = 1,
    ACTIONS(236), 1,
      aux_sym_string_token2,
  [1216] = 1,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
  [1220] = 1,
    ACTIONS(240), 1,
      anon_sym_SQUOTE,
  [1224] = 1,
    ACTIONS(242), 1,
      sym_number,
  [1228] = 1,
    ACTIONS(244), 1,
      aux_sym_comment_token2,
  [1232] = 1,
    ACTIONS(246), 1,
      anon_sym_EQ,
  [1236] = 1,
    ACTIONS(248), 1,
      aux_sym_string_token1,
  [1240] = 1,
    ACTIONS(250), 1,
      anon_sym_LBRACE,
  [1244] = 1,
    ACTIONS(252), 1,
      sym_variable_name,
  [1248] = 1,
    ACTIONS(254), 1,
      sym_variable_name,
  [1252] = 1,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
  [1256] = 1,
    ACTIONS(258), 1,
      anon_sym_SLASH,
  [1260] = 1,
    ACTIONS(260), 1,
      anon_sym_in,
  [1264] = 1,
    ACTIONS(262), 1,
      aux_sym_comment_token1,
  [1268] = 1,
    ACTIONS(240), 1,
      anon_sym_DQUOTE,
  [1272] = 1,
    ACTIONS(264), 1,
      anon_sym_LBRACE,
  [1276] = 1,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
  [1280] = 1,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
  [1284] = 1,
    ACTIONS(270), 1,
      sym_variable_name,
  [1288] = 1,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
  [1292] = 1,
    ACTIONS(274), 1,
      anon_sym_DQUOTE,
  [1296] = 1,
    ACTIONS(274), 1,
      anon_sym_SQUOTE,
  [1300] = 1,
    ACTIONS(276), 1,
      aux_sym_string_token1,
  [1304] = 1,
    ACTIONS(278), 1,
      aux_sym_string_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 93,
  [SMALL_STATE(5)] = 139,
  [SMALL_STATE(6)] = 185,
  [SMALL_STATE(7)] = 231,
  [SMALL_STATE(8)] = 277,
  [SMALL_STATE(9)] = 298,
  [SMALL_STATE(10)] = 326,
  [SMALL_STATE(11)] = 352,
  [SMALL_STATE(12)] = 378,
  [SMALL_STATE(13)] = 404,
  [SMALL_STATE(14)] = 427,
  [SMALL_STATE(15)] = 446,
  [SMALL_STATE(16)] = 467,
  [SMALL_STATE(17)] = 486,
  [SMALL_STATE(18)] = 505,
  [SMALL_STATE(19)] = 527,
  [SMALL_STATE(20)] = 547,
  [SMALL_STATE(21)] = 567,
  [SMALL_STATE(22)] = 587,
  [SMALL_STATE(23)] = 607,
  [SMALL_STATE(24)] = 629,
  [SMALL_STATE(25)] = 651,
  [SMALL_STATE(26)] = 668,
  [SMALL_STATE(27)] = 682,
  [SMALL_STATE(28)] = 696,
  [SMALL_STATE(29)] = 710,
  [SMALL_STATE(30)] = 726,
  [SMALL_STATE(31)] = 740,
  [SMALL_STATE(32)] = 754,
  [SMALL_STATE(33)] = 768,
  [SMALL_STATE(34)] = 782,
  [SMALL_STATE(35)] = 796,
  [SMALL_STATE(36)] = 812,
  [SMALL_STATE(37)] = 830,
  [SMALL_STATE(38)] = 846,
  [SMALL_STATE(39)] = 860,
  [SMALL_STATE(40)] = 874,
  [SMALL_STATE(41)] = 888,
  [SMALL_STATE(42)] = 902,
  [SMALL_STATE(43)] = 918,
  [SMALL_STATE(44)] = 932,
  [SMALL_STATE(45)] = 951,
  [SMALL_STATE(46)] = 972,
  [SMALL_STATE(47)] = 990,
  [SMALL_STATE(48)] = 1008,
  [SMALL_STATE(49)] = 1026,
  [SMALL_STATE(50)] = 1044,
  [SMALL_STATE(51)] = 1062,
  [SMALL_STATE(52)] = 1080,
  [SMALL_STATE(53)] = 1097,
  [SMALL_STATE(54)] = 1109,
  [SMALL_STATE(55)] = 1122,
  [SMALL_STATE(56)] = 1135,
  [SMALL_STATE(57)] = 1148,
  [SMALL_STATE(58)] = 1158,
  [SMALL_STATE(59)] = 1168,
  [SMALL_STATE(60)] = 1178,
  [SMALL_STATE(61)] = 1188,
  [SMALL_STATE(62)] = 1198,
  [SMALL_STATE(63)] = 1205,
  [SMALL_STATE(64)] = 1212,
  [SMALL_STATE(65)] = 1216,
  [SMALL_STATE(66)] = 1220,
  [SMALL_STATE(67)] = 1224,
  [SMALL_STATE(68)] = 1228,
  [SMALL_STATE(69)] = 1232,
  [SMALL_STATE(70)] = 1236,
  [SMALL_STATE(71)] = 1240,
  [SMALL_STATE(72)] = 1244,
  [SMALL_STATE(73)] = 1248,
  [SMALL_STATE(74)] = 1252,
  [SMALL_STATE(75)] = 1256,
  [SMALL_STATE(76)] = 1260,
  [SMALL_STATE(77)] = 1264,
  [SMALL_STATE(78)] = 1268,
  [SMALL_STATE(79)] = 1272,
  [SMALL_STATE(80)] = 1276,
  [SMALL_STATE(81)] = 1280,
  [SMALL_STATE(82)] = 1284,
  [SMALL_STATE(83)] = 1288,
  [SMALL_STATE(84)] = 1292,
  [SMALL_STATE(85)] = 1296,
  [SMALL_STATE(86)] = 1300,
  [SMALL_STATE(87)] = 1304,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_summarize_command, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_summarize_command, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_list, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_list, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generate_command, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_generate_command, 4, 0, 0), SHIFT(51),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_options, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_options, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regress_command, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_command, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_options_repeat1, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_options_repeat1, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_summarize_command, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_options, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_options, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_options_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_options_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_options_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_options_repeat1, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_options_repeat1, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_foreach_loop, 7, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regress_command, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_summarize_command, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_command, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_statement, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_foreach_loop, 6, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 0),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_of_values_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_of_values_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_of_values_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_of_values_repeat2, 2, 0, 0),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_of_values_repeat2, 2, 0, 0), SHIFT_REPEAT(67),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_of_values, 1, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_of_values, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_of_values_repeat2, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_of_values, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_of_values, 3, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [256] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option_value, 1, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_stata(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "stata",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
